name: CI

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Bootstrap
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
